abstract final class ApiEndpoints {
  static const _auth = '/auth';
  static const login = '$_auth/login',
      register = '$_auth/register',
      google = '$_auth/google';
  static const logout = '$_auth/logout',
      refresh = '$_auth/refresh',
      resetPassword = '$_auth/password/reset';
  static const sendEmailVerification = '$_auth/verify-email/send',
      confirmEmailVerification = '$_auth/verify-email/confirm';
  static const sendPhoneVerification = '$_auth/verify-phone/send',
      confirmPhoneVerification = '$_auth/verify-phone/confirm';
  static const account = '$_auth/account',
      profile = '/usuarios',
      adminUsers = '/admin/usuarios';
  static String adminUser(Object id) => '$adminUsers/$id';
  static const foods = '/foods',
      foodSearch = '$foods/search',
      foodNutrientSearch = '$foodSearch/nutrients';
  static const foodCategories = '$foods/categories',
      foodAverages = '$foods/averages',
      foodRandom = '$foods/random';
  static const foodProteinRanking = '$foods/ranking/protein',
      foodFiberRanking = '$foods/ranking/fiber';
  static const foodLowCalorieRanking = '$foods/ranking/low-calorie',
      calculateMeal = '$foods/calculate-meal';
  static String food(Object id) => '$foods/$id';
  static String calculateFood(Object id) => '${food(id)}/calculate';
  static String categoryFoods(Object id) => '$foodCategories/$id/foods';
  static const meals = '/refeicoes',
      workouts = '/treinos',
      sleepLogs = '/registros-sono',
      waterLogs = '/registros-agua';
  static String meal(Object id) => '$meals/$id';
  static String workout(Object id) => '$workouts/$id';
  static String sleepLog(Object id) => '$sleepLogs/$id';
  static String waterLog(Object id) => '$waterLogs/$id';
  static const sync = '/sync';
}
